BEGIN;

CREATE DATABASE "WebShop"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


CREATE TABLE IF NOT EXISTS public."CATEGORY"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PARENT_CATEGORY_ID" bigint,
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    "DESCRIPTION" text COLLATE pg_catalog."default",
    CONSTRAINT "CATEGORY_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."CITY"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "CITY_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."DELIVERY_METHOD"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "DELIVERY_METHOD_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."ORDER"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "FROM_DATE" date NOT NULL,
    "TO_DATE" date NOT NULL,
    "STATUS_FK" integer NOT NULL,
    "DEL_CITY_FK" integer NOT NULL,
    "DEL_ADDRESS" text COLLATE pg_catalog."default" NOT NULL,
    "DEL_METHOD_FK" integer NOT NULL,
    "PRICE" numeric NOT NULL,
    "PAY_METHOD_FK" integer,
    CONSTRAINT "ORDER_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."ORDER_STATUS"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "ORDER_STATUS_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."PAY_METHOD"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PAY_METHOD_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."PRODUCT"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    "PRICE" numeric NOT NULL,
    "QUANTITY" numeric,
    "UNIT_FK" integer,
    "AVAILABILITY" boolean NOT NULL,
    "CATEGORY_FK" bigint,
    "DESCRIPTION" text COLLATE pg_catalog."default",
    "ORDERED_CNT" numeric NOT NULL,
    "RATING" numeric,
    CONSTRAINT "PRODUCT_pkey" PRIMARY KEY ("ID")
);

COMMENT ON COLUMN public."PRODUCT"."QUANTITY"
    IS 'Количество продукта в одной товарной позиции';

COMMENT ON COLUMN public."PRODUCT"."UNIT_FK"
    IS 'Единица измерения: шт, кг, л...';

CREATE TABLE IF NOT EXISTS public."PRODUCT_X_ORDER"
(
    "PRODUCT_FK" bigint NOT NULL,
    "ORDER_FK" bigint NOT NULL,
    "PRODUCT_QNT" numeric NOT NULL,
    "PRODUCT_PRICE" numeric NOT NULL,
    CONSTRAINT "PRODUCT_X_ORDER_pkey" PRIMARY KEY ("PRODUCT_FK", "ORDER_FK")
);

CREATE TABLE IF NOT EXISTS public."UNIT"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "UNIT_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."USER"
(
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "NAME" text COLLATE pg_catalog."default" NOT NULL,
    "PASSWORD" text COLLATE pg_catalog."default" NOT NULL,
    "REGISTRATION_DATE" date NOT NULL,
    "EMAIL" text COLLATE pg_catalog."default" NOT NULL,
    "PHONE_NUM" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "USER_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."USER_X_ORDER"
(
    "USER_FK" bigint NOT NULL,
    "ORDER_FK" bigint NOT NULL,
    CONSTRAINT "USER_X_ORDER_pkey" PRIMARY KEY ("USER_FK", "ORDER_FK")
);

ALTER TABLE IF EXISTS public."ORDER"
    ADD CONSTRAINT "CITY_fkey" FOREIGN KEY ("DEL_CITY_FK")
    REFERENCES public."CITY" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."ORDER"
    ADD CONSTRAINT "DEL_METHOD_fkey" FOREIGN KEY ("DEL_METHOD_FK")
    REFERENCES public."DELIVERY_METHOD" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."ORDER"
    ADD CONSTRAINT "PAY_METHOD_fkey" FOREIGN KEY ("PAY_METHOD_FK")
    REFERENCES public."PAY_METHOD" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."PRODUCT"
    ADD CONSTRAINT "CATEGORY_fkey" FOREIGN KEY ("CATEGORY_FK")
    REFERENCES public."CATEGORY" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."PRODUCT"
    ADD CONSTRAINT "UNIT_fkey" FOREIGN KEY ("UNIT_FK")
    REFERENCES public."UNIT" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."PRODUCT_X_ORDER"
    ADD CONSTRAINT "ORDER_FK" FOREIGN KEY ("ORDER_FK")
    REFERENCES public."ORDER" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."PRODUCT_X_ORDER"
    ADD CONSTRAINT "PRODUCT_fkey" FOREIGN KEY ("PRODUCT_FK")
    REFERENCES public."PRODUCT" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."USER_X_ORDER"
    ADD CONSTRAINT "ORDER_fkey" FOREIGN KEY ("ORDER_FK")
    REFERENCES public."ORDER" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."USER_X_ORDER"
    ADD CONSTRAINT "USER_fkey" FOREIGN KEY ("USER_FK")
    REFERENCES public."USER" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;

